name: journey_stepper
description: "Journey stepper to create the timeline of the journey"
version: 0.0.4
homepage: https://github.com/sagarkoju

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/
